const output = [
    "Sede [lik] i [lik] [lokacija]. Dolazi [lik] i kaže: \"[citat]\" [takotada] je [lik] upoznao Arkana.",
    "Sede [lik] i [lik] [lokacija]. Dolazi [lik] i kaže: \"[citat]\" [takotada] je [lik] upoznao Medlin Olbrajt.",
    "Sede [lik] i [lik] [lokacija]. Dolazi [lik] i kaže: \"[citat]\" [takotada] [dogadjaj].",
    "Sede [lik] i [lik] [lokacija]. Dolazi [lik] i kaže: \"[desavanje] [lik].\" Tako [dogadjaj].",
    "Kad smo jednom [lik] i ja sedeli [lokacija], ja sam pitao da li je istina da [dogadjaj]?"
];

const lik = [
    "Bora Pekić",
    "Fra Sotona Majstorović",
    "Starac Vukašin iz Klepaca",
    "Bugojanska grupa",
    "Pompidu",
    "Pompiduova žena",
    "moj prijatelj Denis Kuljiš",
    "Milorad Pavić",
    "Zvonko, Vučko i Gaga",
    "Stane Dolanc",
    "Stevo Krajačić",
    "Džemal Bijedić",
    "Stevica Marković",
    "Momo Kapor",
    "Rade Marković",
    "tvoj otac",
    "Goran Bregović",
    "Jovo Kapa",
    "Ivan Stambolić",
    "Makavejev i Žika Pavlović",
    "Spasoje Vlajić",
    "Vuk Drašković",
    "Matija Bećković",
    "Jelka Kljajić-Imširović",
    "Pop Đujić",
    "Milić od Mačve",
    "Kusturica",
    "Ranko Rubežić",
    "Đinđić",
    "Šešelj",
    "Ante Marković",
    "Alija Izetbegović",
    "Nebojša Pajkić",
    "Aleksa Đilas",
    "Franjo Tuđman",
    "Mihiz",
    "jedan čika-Duško Radović",
    "Dražen Budiša",
    "Jovica Stanišić",
    "Ljubiša Ristić",
    "Nikola Kavaja",
    "Bora Jović",
    "General Kadijević",
    "Miljenko Hrkać",
    "Bruno Bušić",
    "Darko Ašanin",
    "pokojni Patrijarh Pavle",
    "Ljuba Zemunac",
    "Voja Amerikanac",
    "MASPOK",
    "Giška",
    "Beli",
    "Milovan Danojlić",
    "Tapi",
    "Milovan Đilas",
    "umirovljeni general Janko Bobetko",
    "neshvaćena i od svih napuštena diva Sonja Savić",
    "Kalajićeva ćerka sa testerom u ruci",
    "Vlado Gotovac",
    "Radomir Konstantinović",
    "Vojin Dimitrijević",
    "Danko Popović",
    "Slavoj Žižek",
    "Slavko Ćuruvija",
    "Ratko Dražević",
    "Vučelić, Vučinić i Vulin",
    "Slobodan Selenić",
    "mati Irina (Veselinka Zastavniković)",
    "SDB"
];

const takotada = [
    "Tako",
    "Tada",
    "Onda",
    "Tada",
    "Te večeri",
    "Narednog jutra",
    "Te nedelje",
    "Za par dana",
    "Sutradan",
    "Svakog dana do kraja života",
    "Nije prošlo sat vremena, već"
];

const desavanje = [
    "Ubijen je",
    "Uhapšen je",
    "Poslao me",
    "Došao je",
    "Pao je ",
    "Častio je",
    "Napadnut je",
    "Višestruko je nagrađen",
    "Kidnapovan je",
    "Streljan je",
    "Likvidiran je",
    "Unapređen je",
    "Silovan je",
    "Poslat je u Kumrovačku školu",
    "Ucenjen je",
    "Prokockao se",
    "Optužen je"
];

const lokacija = [
    "u bifeu Energoprojekta",
    "u Klubu Književnika",
    "u Maderi",
    "sa albanskim iredentistima",
    "u Kajmakčalanu",
    "kod Kangrge u Zagrebu",
    "u disidentskim krugovima",
    "u Mornaru",
    "u Dugi",
    "na Osmoj sednici",
    "u Lepoglavi",
    "u vili Alena Delona",
    "kod Dan Tane u restoranu ",
    "među jugoslovenskim slikarima na Monmartru",
    "u Trećem odeljenju UBPOK-a",
    "u Zabeli",
    "na Korčuli sa Ljubom Tadićem",
    "u skupštinskom bifeu",
    "u Grmeču",
    "u bifeu Ateljea 212",
    "sa Ademom Demaćijem",
    "u rezidenciji Popa Đujića u San Markosu, Kalifornija",
    "u kafani Jugović u Čikagu",
    "u vili u Karađorđevu",
    "u filmu \"Plastični Isus\" Lazara Stojanovića",
    "u hotelu \"Mažestik\"",
    "u Poslednjoj šansi na tajnoj proslavi srpske Nove godine",
    "u Nani",
    "u tajnom bunkeru Dobrice Erića u Gruži",
    "u čuvenom beogradskom \"Bermudskom trouglu\"",
    "u vili Mir",
    "u Titovoj rezidenciji na Visu",
    "na Brionima",
    "u stanu Dragomira Olujića",
    "u Vašingtonu na molitvenom doručku ",
    "u Dubravi",
    "na Ibarskoj magistrali",
    "u nekoj kancelariji 4. policijske uprave"
];

const citat = [
    "Mamu vam jebem, sav ste viski popili!",
    "Jel to neko novo \"Načertanije\"?",
    "Nema više leda za viski.",
    "Pavelić je u Argentini.",
    "Gde si ti branio Srbe, tamo ih više nema.",
    "Nećete vi mojim kurcem gloginje mlatit!",
    "Slovenci traže nezavisnost.",
    "Pala je Krajina.",
    "Jedino ovde sam video više Srba na jednom mestu nego na Rankovićevoj sahrani!",
    "Samo ja smem to da kažem Titu!",
    "Samo ti, dijete, radi svoj posao.",
    "Koča je krenuo ka Lopudu u podvodni ribolov.",
    "Upoznao sam Arkana.",
    "Umro je drug Tito.",
    "Srbi nisu u sukobu sa svetom, već sa samima sobom, vraćajući se na šajkaču i opanak iz kojih su jedva izašli.",
    "Malo smo vas ovde pobili!",
    "Ja sam se u to vreme družio samo sa neprijateljskom emigracijom, četnicima i ustašama.",
    "Koliko košta ta vaša srpska krv? Koliko košta Kajmakčalan? Da platimo - pa da budemo mirni!",
    "Ne pakovati Tuđmanu!",
    "Taj šešir mi je iznimno drag jer sam ga dobio od Krleže.",
    "Od glavnog američkog saveznika na Balkanu, postali smo novi nacisti!",
    "Vama su Srbi dobri jedino mrtvi.",
    "Milošević traži garancije za sebe i porodicu.",
    "Mrtvi ste obojica!",
    "Vi, kaže, meni treba spomenik da dignete!",
    "Mrtvi ste obojica, i vi i [lik]!",
    "Meni je to pričao Mimara još osamdesetih godina.",
    "[lik] hoće da razgovara sa vama.",
    "Da li je istina da [dogadjaj]?"
];

const dogadjaj = [
    "je počelo Hrvatsko proleće",
    "je izvršen atentat na Pavelića",
    "je organizovan deveti mart",
    "je organizovan peti oktobar",
    "se on hvalio da je čovek koji je ubio hiljadu ljudi i spavao sa hiljadu žena",
    "sam samo slušao i divio se njegovoj erudiciji",
    "je napravljen nacrt Dejtona",
    "je podeljen Sandžak",
    "je Dolanc uporno zataškavao zločin nad Đorđem Martinovićem",
    "je pala Republika Srpska Krajina",
    "je Pavelić pronađen u Argentini",
    "je Milošević ušao u predsedništvo",
    "je održana poslednja sednica KPJ",
    "su Srbi izgubili trećinu svojih teritorija",
    "je Veljko Vlahović taj film zabranio i on više nikad nije prikazan",
    "je napravljen nacrt Memoranduma SANU",
    "je odbijen predlog plana Z-4",
    "nikad nije pokušan proboj Jasenovca",
    "će pristati na podelu Kosova",
    "je ukinut Informbiro",
    "je beatifikovan Stepinac",
    "je izvršen atentat na ambasadora Rolovića",
    "je izdao Mustafu Golubića Gestapou",
    "je na kraju ostvario ono što je zacrtano još na Drezdenskom kongresu",
    "je to sve snimio Titov kuvar",
    "je meni to ispričala Latinka Perović, a ne znam da li bi smela da potvrdi danas",
    "se dogodio bombaški napad u bioskopu 20. oktobar",
    "je [lik] priveden na saslušanje",
    "je počelo suđenje čuvenoj Beogradskoj šestorci",
    "je organizovana tribina Otvorenog univerziteta",
    "je Šešelj silovan u zatvoru u Zenici i nazvan Balerina"
];

const image = "https://drive.google.com/uc?export=view&id=1Xsj1TE2KifNiAk7R9iTit0jKge7Jnq3c";

module.exports = {
    output,
    lik,
    takotada,
    desavanje,
    lokacija,
    citat,
    dogadjaj,
    image
}