const output = [
    "[intro] [celebfemale] [location] [verbfemale] [object] [whose] [postfix]",
    "[intro] [celebmale] [location] [verbmale] [object] [whose] [postfix]",
    "[intro] [celebfemale] [location] [verbfemale] [objectPerson] [postfix]",
    "[intro] [celebmale] [location] [verbmale] [objectPerson] [postfix]",
    "[intro] [celebfemale] [verbfemale] [objectPerson] [postfix]",
    "[intro] [celebmale] [verbmale] [objectPerson] [postfix]",
    "[intro] [celebfemale] [verbfemale] [object] [whose]",
    "[intro] [celebmale] [verbmale] [object] [whose]"
];

const intro = [
    "PROPAGANDA!",
    "SKANDALOZNO!",
    "SAZNAJEMO!",
    "EKSKLUZIVNO!",
    "OD OVOGA SE LEDI KRV U ŽILAMA:",
    "STRAŠNO!",
    "NEVEROVATNO!",
    "NEĆETE VEROVATI!",
    "BRUTALNO!",
    "NIKAD GORE!",
    "NESVAKIDAŠNJA SCENA!",
    "PROČULO SE!"
];

const celebfemale = [
    "Vesna Vukelić Vendi",
    "Nataša Bekvalac",
    "Olja Karleuša",
    "Zorica Marković",
    "Žena poznatog bodibildera",
    "Devojka poznatog tajkuna",
    "Dara Bubamara",
    "Darija Kisić Tepavčević",
    "Lepa Brena",
    "Jovana Jeremić",
    "Vesna Dedić",
    "Maca Diskrecija",
    "Stanija",
    "Naša poznata YouTuberka Zorannah",
    "Naša seksi misica",
    "Vedrana Rudan",
    "Opra Vinfri",
    "Eva Ras",
    "Vesna Rivas",
    "Nada Macura",
    "Seka Aleksić",
    "Luna Đogani",
    "Poznata farmerka",
    "Poznata zadrugarka",
    "Maja Nikolić",
    "Dara Bubamara",
    "Ceca Ražnatović",
    "Aja Jung",
    "Atina Ferari",
    "Jami",
    "Karleuša",
    "Severina"
];

const celebmale = [
    "Mitar Mirić",
    "Muž naše najveće zvezde",
    "Mladić",
    "Marinko Rokvić",
    "Bivši muž Goce Tržan",
    "Sadašnji dečko Soraje Vučelić",
    "Keba",
    "Jedan prominentni političar",
    "Lepomir Bakić",
    "Predsednik Moldavije",
    "Predsednik Azerbejdžana",
    "Poznati zadrugar",
    "Poznati farmer",
    "Miloš Bojanić",
    "Miša Vacić",
    "Zamenik gradonačelnika, Goran Vesić",
    "Željko Mitrović",
    "Vučićević",
    "Dr Nestorović",
    "Otac Miljaninog deteta",
    "Zadrugar",
    "Instagramer",
    "Poznati homoseksualac",
    "Frizer Vjerice Radete",
    "Čuvar psa Jovane Jeremić",
    "Sin crnogorskog tajkuna"
];

const location = [
    "ispod kreveta",
    "na Tašmajdanu",
    "u Hali Pionir",
    "u Beogradu",
    "na Adi Bojani",
    "na Korčuli",
    "na luksuznoj jahti",
    "u jednom elitnom beogradskom restoranu",
    "na privatnoj korona žurki",
    "u supermarketu",
    "na jednoj beogradskoj pijaci",
    "na Brijunima",
    "u Trstu",
    "na sred kancelarije",
    "u kafani na Ibarskoj magistrali",
    "u OŠ Sava Kerković",
    "na Lastinoj stanici",
    "na privatnom bazenu",
    "u svom skromnom domu",
    "u svom dvorištu",
    "na heliodromu",
    "na beogradskom aerodromu Nikola Tesla",
    "u policijskoj stanici",
    "na sudu",
    "u galeriji slika",
    "u Prvom osnovnom sudu",
    "u poreskoj upravi",
    "na Sajmu",
    "u svečanoj sali OŠ Sava Kerković",
    "u Domu sindikata",
    "u Beogradskoj Areni",
    "u svojoj raskošnoj kući na Bežanijskoj kosi",
    "na krevetu",
    "na stepenicama vlade",
    "u liftu kovid bolnice",
    "u Rovinju",
    "na haubi automobila",
    "na gradilištu Beograda na vodi",
    "u Sava Centru",
    "na gliseru",
    "na krovu višespratnice",
    "na Kliničkom centru",
    "nasred autoputa Miloš Veliki",
    "na graničnom prelazu Kelebija",
    "na Batrovcima",
    "u Skoplju",
    "na Zlatiboru",
    "u apartmanima koje izdaje Nada Topčagić",
    "u kafani Zorice Marković"
];

const verbfemale = [
    "našla",
    "videla",
    "ukrala",
    "mirisala",
    "šmekala",
    "gledala",
    "mazila",
    "milovala",
    "spazila",
    "bacila",
    "tresla",
    "pipala",
    "pipkala",
    "krila",
    "pokušala da popije",
    "naišla na",
    "gladila",
    "cepala",
    "ljubila",
    "grlila",
    "molestirala",
    "primila",
    "tukla",
    "šamarala",
    "čuvala",
    "čistila",
    "prala",
    "zaskakala",
    "otela"
];

const verbmale = [
    "našao",
    "video",
    "ukrao",
    "mirisao",
    "šmekao",
    "gledao",
    "mazio",
    "milovao",
    "spazio",
    "bacio",
    "tresao",
    "pipao",
    "pipkao",
    "krio",
    "pokušao da popije",
    "naišao na",
    "gladio",
    "cepao",
    "ljubio",
    "grlio",
    "molestirao",
    "primio",
    "tukao",
    "šamarao",
    "čuvao",
    "čistio",
    "prao",
    "zaskakao",
    "oteo"
];

const object = [
    "prljave gaće",
    "negativan PCR test",
    "votku",
    "špil karata",
    "korišćen prezervativ",
    "špric",
    "kolonjsku vodu",
    "dnevnik",
    "parfem",
    "toalet papir",
    "glasački listić",
    "kompjuter",
    "vagu za merenje",
    "galijumski toplomer",
    "macinu travu",
    "gole slike",
    "ulaznicu za EXIT",
    "vrata sa zgrade",
    "garažno mesto u Belvilu",
    "pozitivan PCR test",
    "antigenski test",
    "Fajzerovu vakcinu",
    "Astrazeneku",
    "mačku",
    "psa",
    "šiške",
    "zalizanu kosu",
    "mali prst",
    "vaginalete",
    "tampone",
    "kondome",
    "vlasnice lanaca poznatih hotela",
    "popušen džoint",
    "kokain",
    "sitno granje",
    "prašinu u beogradskom tramvaju",
    "odeću",
    "tepihe",
    "zlatni escajg",
    "mudru spremačicu",
    "savete",
    "salvete",
    "struk",
    "noge",
    "bedra",
    "nos",
    "silikonske grudi",
    "usta",
    "rastvor sumporne kiseline",
    "privatnu kolekciju",
    "persijske tepihe",
    "pozlaćenu olovku",
    "paket LEGO kocki",
    "kartu za Beogradski metro",
    "parket",
    "cipele",
    "sandale",
    "skije",
    "čizme",
    "čarape",
    "ruž",
    "prste",
    "palac",
    "kolena",
    "porno snimak",
    "zavodljive oči",
    "uzani struk",
    "ručak",
    "traktor",
    "smartfon"
];

const whose = [
    "bivšeg muža Goce Tržan",
    "bivše žene poznatog zadrugara",
    "sadašnjeg dečka Soraje Vučelić",
    "Senidinog prvog komšije",
    "muža svoje komšinice",
    "Kristine Bekvalac",
    "muža Seke Aleksić",
    "jednog važnog srpskog biznismena",
    "zgodne starlete",
    "naše poznate tiktokerke",
    "ove devojke sa naslovne strane",
    "Jelene Đoković",
    "poznatog instagram influensera",
    "poznate instagram influenserke",
    "babe Novaka Đokovića",
    "psa Dare Bubamare",
    "najboljeg druga Sekinog muža",
    "jedne seksi Slovenke",
    "jednog zgodnog Bosanca",
    "roditelja Marije Šerifović",
    "Merime Njegomir",
    "družine Pere Kvržice",
    "sijamskog pitona",
    "svoje persijske mačke",
    "razredne Jovane Jeremić iz OŠ Sava Kerković",
    "klijentkinje svog pašenoga",
    "jetrve Nikole Rokvića",
    "spremačice Jelene Rozge",
    "Maje Nikolić",
    "bivšeg nevenčanog supruga Maje Nikolić, kuma Crkve presvete Bogorodice u Ahenu",
    "Zorice Marković",
    "Lepe Lukić",
    "Novakovog psa Pjera",
    "sina Sinana Sakića",
    "komšije pokojnog Džeja",
    "svog najboljeg gej druga",
    "svoju najbolju drugaricu",
    "Milomira Marića",
    "Bogoljuba Karića",
    "Verice Rakočević",
    "muža Verice Rakočević",
    "Vjerice Radete",
    "Sani Armani",
    "Karamele",
    "Ivane Sirene"
];

const objectPerson = [
    "Zoricu Marković Kevu",
    "Lepu Lukić",
    "Lepomira Bakića",
    "Ivanu Sirenu",
    "Cecu Ražnatović",
    "Lepu Brenu",
    "služavku Dragane Mirković",
    "Draganu Mirković",
    "Natašu Kandić",
    "Sonju Biserko",
    "poznatog voditelja",
    "Zorana Ćumuru",
    "Maju Nikolić",
    "Irenu Sjekloću Miler",
    "Zoranu Pavić",
    "Vojislava Šešelja",
    "Ivicu Dačića",
    "ženu Zorana Babića",
    "Jovanu Joksimović",
    "Željka Joksimovića",
    "Mariju Šerifović",
    "Uraganke",
    "Knezovu ćerku",
    "Cecinu decu",
    "Karleušine ćerke",
    "Anabelu Đogani",
    "Nadu Topčagić",
    "Đanija",
    "Vesnu Rivas"
];

const postfix = [
    "",
    "[FOTO]",
    "[VIDEO]",
    "[SISE]",
    "[FOTO] [VIDEO]",
    "[FOTO] [SISE]",
    "[VIDEO] [SISE]",
    "[FOTO] [VIDEO] [SISE]"
];

const image = "https://drive.google.com/uc?export=view&id=12jCcyN8OKdQmckX0DjqKOEgDZTDh48l3";

module.exports = {
    output,
    intro,
    celebfemale,
    celebmale,
    location,
    verbfemale,
    verbmale,
    object,
    whose,
    objectPerson,
    postfix,
    image
};