const kraj = [
    "govnarčina",
    "pijandura",
    "kurvetina",
    "kurveštija",
    "kamenjarka",
    "droljetina",
    "debilčina",
    "narkomančina",
    "gadura",
    "degenčina",
    "kretenčina",
    "idiotčina",
    "balvančina",
    "mamlazčina",
    "smrlja",
    "guzica",
    "guzičetina",
    "majmunčina",
    "ameba",
    "bakterija",
    "konjina",
    "krava",
    "volčina",
    "magarčina",
    "prostitutka",
    "štroka",
    "prljavština",
    "prašina",
    "botčina",
    "gromada",
    "invalidčina",
    "pičketina",
    "pampurčina",
    "šiljokurančina",
    "masturbacija",
    "drkica"
];

const atribut = [
    "lojava",
    "gnojava",
    "smrdljiva",
    "degenerična",
    "raspala",
    "pederska",
    "razmetljiva",
    "slinava",
    "balava",
    "štrokava",
    "grozomorna",
    "paraplegična",
    "felerična",
    "retardirana",
    "maloumna",
    "psihopatska",
    "najlonarska",
    "narikačka",
    "bezmozgaška",
    "padavičarska",
    "pajdomanska",
    "kmeturska",
    "kurvinska",
    "sodomska",
    "seratorska",
    "pampuljarska",
    "bludnička",
    "dramoserska",
    "šiljokuranska",
    "gmazolika",
    "potočarska",
    "seljačka",
    "gradska",
    "pičkarska",
    "kurčeva"
];

//TODO Image - mozda emoji koji je ljut??
const image = 'https://i.imgur.com/PFhkB6T.png';

module.exports = {
    kraj,
    atribut,
    image
};