const poslovica = [
    "Ako budeš most, svako će da te gazi",
    "Ako drugog poštuješ za sebe ne brini.",
    "Ako dugo žive skupa, životinje se zavole, a ljudi se zamrze.",
    "Ako želiš izgubiti prijatelja, posudi mu novac .",
    "Ako želiš izgubiti prijatelja, pričaj s njim o politici.",
    "Ako želiš jezgro, slomi ljusku",
    "Ako ženu tučeš, svoju sreću tučeš.",
    "Ako zagrmi na Svetog Iliju, neće biti lešnika",
    "Ako zahteva napor, nije ga vredno raditi",
    "Ako znaš šta ti je bilo, ne znaš šta će ti biti.",
    "Ako imaš mašice, ne hvataj vatru rukama",
    "Ako ih ne možeš pobediti pridruži im se",
    "Ako je go, ali je soko.",
    "Ako je i koliba, naša je.",
    "Ako je i teško živeti, opet je život sladak",
    "Ako je na guvnu, nije u ambaru",
    "Ako je neko lud, ne budi mu drug.",
    "Ako jedna želja nije zadovoljena to je dovoljan razlog.",
    "Ako kupuješ često ono što ti ne treba, skoro ćeš prodavati ono što ti treba",
    "Ako mi ne možeš pomoći, nemoj mi odmagati.",
    "Ako ne može po konju.",
    "Ako ne možemo kako hoćemo, a mi kako možemo",
    "Ako ne počneš, nećeš ni završiti",
    "Ako ne umije reći, umije leći.",
    "Ako neće zlo od tebe, beži ti od zla.",
    "Ako odgovaraš na poruku bit ćeš još više naoružan.",
    "Ako si ti vuk, nijesam ni ja ćuk.",
    "Ako ti mogu kupiti kapu, pamet ne mogu.",
    "Ako u starosti želiš odmor, moraš u mladosti uneti napor",
    "Ako hoćeš da pljuneš, pljuni u šaku.",
    "Ako hoćeš koga da poznaš, podaj mu vlast.",
    "Ako činiš dobro, ne udaraj u veliko zvono.",
    "Ako si lud, ostani lud",
    "Ako slepac slepca vodi, obojica će u jamu upasti.",
    "Badava je dobro seme kad je rđavo oranje.",
    "Batina ima dva kraja.",
    "Bez alata nema ni zanata.",
    "Bez društva nema junaštva.",
    "Bez jednoga čoveka može vašar biti",
    "Bez muke nema nauke.",
    "Bez zanata nema alata.",
    "Beri želje pokraj sebe!",
    "Bi se na srebrnoj pari obrnuo.",
    "Bivši prijatelj je gori nego neprijatelj.",
    "Bijele ruke tuđ posao miluju.",
    "Biser ne valja pred svinje prosipati.",
    "Bježi kud ti je volja, od sebe ne utječe.",
    "Blago nestade, vrag ostade.",
    "Blago onom ko se tuđom štetom opameti, a teško onom koji svojom mora",
    "Blago onome ko zna da ne zna, a hoće da zna.",
    "Bog je spor, ali dostižan.",
    "Bog ne plaća svake subote.",
    "Bez Boga ni preko praga.",
    "Bog onda pomaže kad niko ne može.",
    "Bogat je ko nije dužan, a mlad ko je zdrav.",
    "Bogat je onaj koji više proizvede, nego što pojede.",
    "Bogata je teško darovati, sita gosta još teže častiti.",
    "Bogatstvo menja čud, retko nabolje.",
    "Bogatstvo nikad nije sito.",
    "Boj ne bije svijetlo oružje, već boj bije srce u junaka.",
    "Bol se savlada strpljivošću.",
    "Bolan se pita, a zdravom se daje.",
    "Bolest na kolima dolazi, a na dlaku izlazi.",
    "Bolja je poštena smrt nego sramotan život.",
    "Bolja je svoja proja nego tuđa pogača.",
    "Bolje da te smrt prijeka digne, nego suza siromaška stigne.",
    "Bolje i dvared pitati nego jedared zaići.",
    "Bolje saviti nego slomiti.",
    "Bolje nepravdu trpiti, nego činiti.",
    "Bolje obići šumu, nego na prečcu sresti vuka.",
    "Bolje iz daleka se voleti, nego izbliza mrzeti.",
    "Bolje poslednji među dobrim, no prvi među zlim.",
    "Bolje ikad nego nikad.",
    "Bolje je dobro slušati, nego loše zapovedati.",
    "Bolje je dobroga služiti, nego rđavu zapovijedati.",
    "Bolje je i malo s blagoslovom, negoli i dosta s prokletstvom.",
    "Bolje je imati rđavu godinu, nego rđava susjeda.",
    "Bolje je ne početi, nego ne dočeti.",
    "Bolje je neznalica no tvrdoglavica.",
    "Bolje je nemati, nego otimati.",
    "Bolje je nešto ne znati nego naopako i zlo znati",
    "Bolje je pokliznuti nogom nego jezikom.",
    "Bolje je s mudrim plakati nego s ludim pevati.",
    "Bolje je svašta jesti, nego svašta govoriti.",
    "Bolje je svoje jaje nego tuđa kokoš.",
    "Bolje je u kolibi pjevati nego u dvoru plakati.",
    "Bolje je umeti nego imati",
    "Bolje mršav mir nego debela parnica.",
    "Bolje prazna kesa nego prazna glava",
    "Bolje s mudrim orati nego s ludim vino piti",
    "Bolje se zamjeriti Bogu, no narodu.",
    "Bolje se ograditi dobrim komšijom nego dobrom ogradom.",
    "Bolje se od po puta vratiti nego rđavim do kraja ići",
    "Bolje se s junakom biti, nego s rđom ljubiti.",
    "Bolje slep očima, nego slep pameću.",
    "Bolje suv hleb s poštenjem nego kolač s nepoštenjem",
    "Bolje ukor mudroga, nego hvala ludoga",
    "Bolje džabe sedeti, nego džabe raditi.",
    "Bolji je dobar glas nego zlatan pas.",
    "Bolji je i crn kolač nego prazna torba.",
    "Bolje vrabac u ruci, nego golub na grani.",
    "Brat brata nad jamu vodi, ali u jamu ne meće.",
    "Brat je mio ma koje vere bio (kad bratski čini i postupa).",
    "Brdo se s brdom ne može sastati, a živi se ljudi sastanu.",
    "Budalu ne treba tražiti, sama se javi.",
    "Vatra i voda su dobre sluge, ali zli gospodari",
    "Velike ribe veliku vodu traže",
    "Veselo srce pola zdravlja",
    "Veća glava više glavobolje",
    "Vinograd ne ište molitve, nego motike",
    "Više valja gram pameti nego oka snage",
    "Više je ljudi pomrlo od jela i pića nego od gladi i žeđi",
    "Više um zamisli nego more ponese",
    "Vješt goru lomi, a nevješta gora",
    "Vo se veže za rogove, a čovjek za jezik.",
    "Voda svašto opere, do crna obraza.",
    "Vodu koju ćeš pit nemoj mutit.",
    "Vreme gradi niz Kotare kule, vreme gradi vreme razgrađuje",
    "Vreme donese sve ko ga dočekati ume",
    "Vreme je najveći gospodar",
    "Vuk dlaku mijenja, ali ćudi nikada.",
    "Vuk ne vije što je mesa gladan, nego vije da družinu svije",
    "Gvožđe reže i drvo i kamen, ali i njega rđa jede.",
    "Gvožđe se kuje dok je vruće.",
    "Gde žena buči tu muž muči.",
    "Gde zlato govori, usta ćute.",
    "Gde zlato gospoduje, razlog se ne čuje.",
    "Gde je mnogo priče malo je rada.",
    "Gde je sila gospodar, pravda je sluga",
    "Gde je sloga tu je i pobeda",
    "Gde je sova izlegla sokola?",
    "Gde je stida, tu je i poštenja.",
    "Gde je cvet, tu je i med",
    "Gde je čija kuća tu je i sredina sveta.",
    "Gde miš ne cijuče, tu ni pile ne pijuče.",
    "Gde nije mira, nema ni sreće",
    "Gde se ništa ne može pomoći lepo je osmehnuti se.",
    "Gde se pije primakni se, gde se bije odmakni se.",
    "Gdje nema vola orača, tu nema ni kolača",
    "Ginu ti što se smeju uoči bitke.",
    "Glava je starija od knjige.",
    "Glad je najbolji kuvar",
    "Glad očiju nema.",
    "Gladan pas i na gazdu laje.",
    "Gladnog ne teši, već nahrani.",
    "Gle Miloša, pope se na plot!",
    "Govori kao bez vilica.",
    "Govori u bespuće.",
    "Gospodskom smijehu i vedru nebu ne valja vjerovati, jer se začas promijeni.",
    "Gradi ražanj, a zec u šumi.",
    "Dobro čini ne boj se, zlo čini nadaj se.",
    "Da ga zemlja ne vuče sebi, poleteo bi.",
    "Da ga čoek pošalje po smrt, mogao bi se naživljeti.",
    "Da je srce tvrđe od kamena opet bi ga rastopilo zlato.",
    "Da je steći ko što reći, svi bi bogati bili.",
    "Da je švati ko zjati, i vrana bi košulju nosila.",
    "Da ne bole, ne b' se rane zvale.",
    "Da nije vetrova, pauci bi nebo premrežili.",
    "Da padne na leđa, razbio bi nos.",
    "Da se prava istina pozna, treba čuti dva zvona.",
    "Dan se hvali kad veče, a život kad smrt dođe",
    "Danas vezir, sjutra rezil.",
    "Danas u zlatu, sutra u blatu.",
    "Darovni kolač često u grlu zapne.",
    "Dva loša ubiše Miloša",
    "Dva lješnika, orahu su vojska.",
    "Dva puta mjeri, a treći kroj.",
    "Dvaput zine – triput slaže",
    "Devojka koja žuri na sastanak već je zakasnila.",
    "Dobavio se ki ćelav kape.",
    "Dobar glas daleko ide, a zao još dalje",
    "Dobar espap lasno kupca nađe.",
    "Dobar posao se sam hvali",
    "Dobar čovek uvek ostaje početnik.",
    "Dobra žena poštuje muža, pa da je kao pevac.",
    "Dobra žena praznu kuću čini da je puna.",
    "Dobra krava se i u štali proda!",
    "Dobra nije gde se pametni ne slušaju.",
    "Dobra ovca mnogo ne bleji, ali mnogo vune daje.",
    "Dobra čeljad uvek posla nađu",
    "Dobre komšije podižu cenu kući i dobrom imanju.",
    "Dobro je kašto i pametnu ženu poslušati",
    "Dobro je lasno zaboraviti, a zlo nikada.",
    "Dobro je teško videti, a lako se pozna.",
    "Dobro jelo samo se nudi",
    "Dobro mi je i boljem se nadam.",
    "Dobro obrađena zemlja nikad nije jalova",
    "Dobro se ne pozna dok se ne izgubi.",
    "Dobrom konju ne treba mamuza.",
    "Dobru čoveku sve dobro stoji.",
    "Dogovorna je najbolja.",
    "Dok dete ne padne, ne može naučiti da hoda",
    "Dok živiš, dolikuje ti da se nadaš.",
    "Dok je leđa, biće samara.",
    "Dok je raje i muka, biće i hajduka",
    "Dok je šiba tanka, treba je ispravljati.",
    "Dok lipa cveta, prepuna je pčela",
    "Dok svi kažu 'E vala!' - osta glava ćelava.",
    "Dok se mudri namudrovaše, ludi se naživovaše.",
    "Dok se muke ne namuči, pameti se ne nauči",
    "Dokle prosi, zlatna usta nosi, a kad vraća, pleća obraća.",
    "Dragom često opraštaj, sebi nikad.",
    "Drvo bez grane i čovek bez mane - ne mogu biti.",
    "Drvo se na drvo oslanja, a čovek na čoveka.",
    "Drž’ se nova puta i stara prijatelja",
    "Drži se novog puta i starog prijatelja.",
    "Drugo doba, druge ćudi",
    "Duboka voda je bistra, a plitka mutna.",
    "Dug je zao drug",
    "Đe brat brata ne voli, tu nema sreće.",
    "Đe velika zvona zvone, tu se mala ne čuju.",
    "Đe dosta ruka pregne, radnja je brzo završena",
    "Đe je sreća, tu je i nesreća.",
    "Đe je tor tu je i mor.",
    "Đe ko nikne, tu i obikne.",
    "Đe nema malenog nema ni golemog.",
    "Đe nije žene, tu nije ni kuće.",
    "Đe nije mačke, tu miši kolo vode.",
    "Đe se god sastanu ljudi, ocjenjuju druge, a sebe ne.",
    "Đe će kruška no pod krušku.",
    "Đeca su kao rosa.",
    "Ekser drži potkov, potkov konja, konj junaka, junak grad, a grad zemlju.",
    "Eto mene, eto vas, eto vama rat sa Turcima.",
    "Eto ti ga,đavole!",
    "E, džaba ga, vala, bilo!",
    "E, ta ti valja!",
    "E, da je baba deda.",
    "Žalost i radost se poznaju čoveku po licu",
    "Žežen kašu hladi",
    "Žena muža nosi na licu, a muž ženu na košulji",
    "Ženi je najslađi zalogaj - muško srce",
    "Ženi sina kad 'oćeš a udaj 'ćer kad možeš!",
    "Ženi sina pa šalji u vojsku",
    "Ženiti se mlad - prerano je, a star - prekasno je.",
    "Ženska lepota je njeno oružje",
    "Žensko je oružje jezik",
    "Žensko je tuđa sreća",
    "Ženu i kosu nikome ne daj",
    "Živ mi Todor da se čini govor.",
    "Živa glava sve podnese i na sve se navikne.",
    "Živ bio, srećan bio, kud god hodio!",
    "Žive ko pas i mačka.",
    "Živeo i Bog te veselio!",
    "Živi ko riba na suvom.",
    "Živi prosto- doživećeš sto.",
    "Živ mi i zdrav bio!",
    "Živ mi ti!",
    "Živ ti ja!",
    "Za brige je teško čuvati lepe devojke.",
    "Za zlato rđa ne prijanja.",
    "Za jedan dobar dan mnogo se zlih pretrpi.",
    "Za majstorom gora plače.",
    "Za nevolju babu vode, kad devojke ne nahode.",
    "Za nevolju i medved igrati nauči.",
    "Za neprijateljem ako i misliš ne govori zlo.",
    "Za čisto zlato rđa ne prijanja.",
    "Zaboravnost je znak lenjosti.",
    "Zavadio bi dva oka u glavi.",
    "Zajedničkom konju, grbava su leđa",
    "Zaklela se zemlja raju da se svake tajne znaju",
    "Zakrvavio očima ko divlji petao.",
    "Zbori pravo pa sedi gde ti drago",
    "Zid ruši vlaga, a čovjeka briga",
    "Zima ne traži ljepote, nego toplote",
    "Zima ujeda bez zuba",
    "Zlatan lanac slobodu ne pruža.",
    "Zlato je čisto i u prljavoj kesi.",
    "Zlato se u vatri prebira, čovek u nevolji",
    "Zlo brzo dođe, a polako prođe",
    "Zlo je ko ne zna a učiti se ne da.",
    "Zloba jede dušu kao rđa gvožđe",
    "Zna se zlato i u đubretu",
    "I vrag zna šta je pravo, ma neće, nego kako mu milo.",
    "I vuk vije jer ga rđa bije!",
    "I zid ima uši, i plot ima oči.",
    "I jedan je neprijatelj mnogo, a sto je prijatelja malo",
    "I kljuse i goveče teži na svoj zavičaj.",
    "I krme rokne kad mu se čovjek javi.",
    "I loncem o kamen ili kamenom o lonac, teško loncu svakojako.",
    "I ljude poslušaj, i svoje pameti imaj.",
    "I najmudriji da proda sve što ima, ne može da kupi sve što nema.",
    "I sunce prolazi kroz kaljava mesta ali se ne okalja.",
    "I crna krava ima bijelo mleko.",
    "Iver ne pada daleko od klade.",
    "Ide vreme, nosi breme.",
    "Iz prazne kuće i miši bježe.",
    "Iza dažda biće i sunca.",
    "Izvalila magla panj.",
    "Izvan očiju, izvan srca.",
    "Izgoreće slama, ali će i miši sesti gde ne valja.",
    "Izreke su ukras govora.",
    "Ili ne pokušavaj, ili dovrši.",
    "Imadoh – ne znadoh, izgubih – poznadoh",
    "Inat babi dušu gubi.",
    "Inat je zao zanat.",
    "Inat je nesrećan zanat.",
    "Ispeci pa reci.",
    "Ispod Mire sto đavola vire.",
    "Isteruje mak na konac.",
    "Istina i žena najlepše su - gole.",
    "Istina i pravda pobeđuju.",
    "Istina je da je svaki general posle rata pametan.",
    "Istina je ono ušta ubediš većinu da veruje.",
    "Istina uvek najviše boli.",
    "Istorija je učiteljica života.",
    "Istorija se ponavlja.",
    "Istoriju pišu pobjednici. To je razlog što je ona puna neistina!",
    "Ja psu, a pas repu, a rep dlaci: idi dlaka ti si laka.",
    "Ja tikvu u vodu, a tikva iz vode.",
    "Jak koren duge mladare pušta.",
    "Jača su dvojica nego sam Radojica",
    "Jače je djelo nego besjeda",
    "Jedan drobi, drugi kusa.",
    "Jedna glava, hiljada jezika.",
    "Jedna greška, večna muka.",
    "Jedna lasta ne čini proleće",
    "Jedna šugava ovca celo stado ošuga.",
    "Jedno krivo drvo ceo tovar raspe",
    "Jedno misli, drugo govori, treće tvori.",
    "Jednog gleda, dvojica se nadaju.",
    "Jednom se lebac lomi.",
    "Jezik je više glava posekao nego sablja.",
    "Jezik kosti nema, ali kosti lomi.",
    "Jeftina roba kasu prazni.",
    "Junakova majka najpre zaplače.",
    "Kad bi se sve pameti iznele na vašar, svak bi se svoje mašio.",
    "Kad Bog daje ne pitaj čiji je sin.",
    "Kad vidim onda ću i verovati.",
    "Kad ideš vuku na čast, povedi psa sa sobom.",
    "Kad je volje i zlo ide na bolje.",
    "Kad je glava luda, sve telo strada",
    "Kad je dobre volje, svega je",
    "Kad je preša: đe si Peša? kad nije preša: oklen si Peša?",
    "Kad lažeš, kreću li ti se zubi.",
    "Kad legneš znači - predao si se.",
    "Kad lisica pridikuje, pazi dobro na guske.",
    "Kad mator pas laje, valja videti šta je",
    "Kad mi ne možeš pomoći, nemoj mi odmagati",
    "Kad najviše grmi, najmanje kiše pada.",
    "Kad se prase naije, ono korito prevali.",
    "Kad se prase najede onda korito prevali.",
    "Kad se slože i slabi su jaki.",
    "Kad si u kolu, valja da igraš",
    "Kad sultan nazebe, raja kija.",
    "Kad čovek tone i za vrelo gvožđe se hvata.",
    "Kad čoek nema svoga dobra, tuđe zlo premeće.",
    "Kakav pozdrav onaki i odzdrav.",
    "Kakav starješina, takva sva opština",
    "Kako došlo onako i prošlo.",
    "Ki da se svaka iščešljana uda!?",
    "Ko besjedi šta hoće, mora slušati sta neće",
    "Ko rano rani dve sreće grabi.",
    "Ko brzo sudi, brzo se i kaje.",
    "Ko vara na testu, vara na svakom mestu.",
    "Ko visoko leti, nisko pada.",
    "Ko voli da radi, dabogda mu se o glavi radilo.",
    "Ko dva zeca vije, ne ulovi nijednog.",
    "Ko dete suviše voli, upropasti ga.",
    "Ko dobro počne, on je na pola radnje.",
    "Ko drugome jamu kopa, sam će u nju pasti.",
    "Ko želi da peva, uvek će naći pesmu.",
    "Ko za tuđom vunom pođe, sam ostrižen kući dođe.",
    "Ko zavisi od drugog, treba i njegovom psu da se umiljava.",
    "Ko zna ne zja.",
    "Ko istinu gudi, gudalom ga po prstima biju.",
    "Ko jarca za rog vuče, njemu je teško.",
    "Ko je jači taj tlači.",
    "Ko je mnogo patio, mnogo je i zapamtio.",
    "Ko jedanput slaže, drugi put mu se ne vjeruje iako istinu kaže",
    "Ko kasno brazdu zaore u jesen čičak obere.",
    "Ko laže za tebe, lagaće i protiv tebe.",
    "Ko lopovu gleda kroz prste i sam je lopov.",
    "Ko lupeža krije, bolji ni on nije",
    "Ko ljeti hladuje, zimi gladuje",
    "Ko ljude ne sluša, ni čovek nije.",
    "Ko me lani bio, ni sad mi nije mio",
    "Ko meće prst među tuđa vrata, otkinuće mu",
    "Ko mnogo zbori - ili mnogo zna ili mnogo laže.",
    "Ko na zvezde laje, ispašće mu zubi.",
    "Ko naglo počne, naglo će i završiti",
    "Ko ne čuva malo, ne može ni dosta imati",
    "Ko ne čuva tuđe, neće imati ni svoje",
    "Ko nema sokola i kukavici se veseli.",
    "Ko nema sreće u sebi neće je naći u svetu.",
    "Ko neće brata za brata, 'oće tuđina za gospodara.",
    "Ko nije služio, ne umije ni zapovjedati.",
    "Ko nosi, ne prosi.",
    "Ko odgoni mačke, vabi miše.",
    "Ko pita ne skita.",
    "Ko pjeva, zlo ne misli",
    "Ko prati tuđ posao, svoj zaboravlja.",
    "Ko rakiju večera, vodu doručkuje",
    "Ko rat želi, kod kuće ga imao.",
    "Ko s vragom tikve sadi, o glavu mu se razbijaju.",
    "Ko sa đavolom tikve sadi o glavu mu se lupaju.",
    "Ko svoj može biti, tuđ nek ne bude.",
    "Ko se Boga ne boji i ljudi ne stidi beži od njega.",
    "Ko se dima ne nadimi, taj se vatre ne ogreja.",
    "Ko se na tuđim kolima vozi, neće daleko otići.",
    "Ko se ne muči u mladosti, kuku mu u starosti.",
    "Ko se ne stidi svoga obraza, neće ni moga.",
    "Ko se ne brani od gnjida, braniće se od vašiju.",
    "Ko se ovcom učini, kurjaci ga izjedu.",
    "Ko se pred jednim klanja, pokazuje drugom leđa.",
    "Ko se rada boji, taj u bedi živi",
    "Ko se seli, taj se ne veseli.",
    "Ko se tuđem zlu veseli, nek se svome nada",
    "Ko se hvali sam se kvari.",
    "Ko seje trnje, ne bere grožđe.",
    "Ko spretnije traži, lakše dobije.",
    "Ko staro ljubi, danke gubi.",
    "Ko staro ne krpi, ni novo ne nosi",
    "Ko ti iskopa oko? Brat rođeni! Odmah sam mislio čim je tako duboko.",
    "Ko traži veće, izgubi iz vreće",
    "Ko tuđ posao gleda, svoj zaboravlja",
    "Ko će naplesti uzica za tuđih gubica?",
    "Ko u krčmu ide, tuđu decu hrani.",
    "Ko u nebo pljuje na obraz mu pada.",
    "Ko umije, njemu dvije.",
    "Ko hoće da ga drugi poštuju, valja najpre da se sam poštuje",
    "Ko hoće časno, ne moze lasno.",
    "Ko čeka i dočeka.",
    "Ko šta zagrize, teško ostavlja.",
    "Koga nije, bez njega se može",
    "Koga su zmije klale i guštera se boji",
    "Koga tišti taj i vrišti.",
    "Kod komšije, trava zelenija",
    "Koja da dvadeset litara varenike.",
    "Koja kokoš mnogo kakoće, malo jaja nosi",
    "Koja se ne rekne, ona se ne čuje.",
    "Koja se ovca od stada odvoji, vuk će je pojesti",
    "Koja se često ogleda, slabo kuću nadgleda.",
    "Koja Crkva ne pomaže, ne valja joj se ni moliti.",
    "Ko je gotov na smrt, nikad nije rob.",
    "Ko je junak? Ko nadvlada svoje strasti.",
    "Koje pseto hoće da ubiju, poviču ~ bijesno je.",
    "Koji konja slamom hrani, sam kola vuče.",
    "Koji se hrt silom u lov vodi, onaj zeca ne hvata",
    "Kojoj ovci svoje runo smeta, onđe nije ni ovce ni runa.",
    "Koliko je nizbrdica onoliko je uzbrdica.",
    "Koliko ljudi toliko ćudi.",
    "Kome je Bog otac, lako mu je biti svetac.",
    "Kome svijet kroji kapu, onaj ide bez kape.",
    "Krv nije voda.",
    "Krivac se i senke boji.",
    "Krpež i trpež po svijeta drže",
    "Kupuj prvo suseda, pa posle kuću.",
    "Kurjak kožom plaća",
    "Kućni prag je najveća planina.",
    "Lavica jedno okoti ali lava.",
    "Laje ko pas na zvezde.",
    "Lako je tuđim kurcem po koprivama mlatiti.",
    "Lako je zdravome bolesnoga savetovati.",
    "Lako je iza šest volova gurati plug.",
    "Lako je ljubav steći, al’ je teško uzdržati",
    "Lako ti je plitku vodu zamutiti i budalu naljutiti",
    "Lakše je skuvati željezo nego savladati ženinu tvrdoglavost.",
    "Lakše je steći nego sačuvati.",
    "Lakše je šta pokuditi nego moći sam učiniti",
    "Lasni je kavgu zametnuti, al je teško kavzi dževap dati.",
    "Lasno je biti s tuđijem dobar",
    "Lasno je govoriti, al’ je teško tvoriti.",
    "Lasno je zdravom bolesnog savetovati",
    "Lasno je pokraj čaša junakom biti.",
    "Lasno je tuđim rukama za vrelo gvožđe hvatati.",
    "Lasno je u Dunav kamen baciti, al ga je teško izvaditi.",
    "Lepu ženu i vinograd pored puta ne treba imati.",
    "Lovac je da lovi, a prepelici da se čuva.",
    "Ludi boj biju, a mudri vino piju.",
    "Ludi se penje da visoko sjede, a kad bude do bjesede, kaje se što onđe sjede.",
    "Ljeti od hlada do hlada, a zimi od jada do jada",
    "Ljubav vera i nada ostavile traga",
    "Ljubav dugo trpi",
    "Ljubav za ljubav, sirenje za pare",
    "Ljubav i sloga nemoguće omoguće",
    "Ljubav je jedina strast koja ne trpi prošlost, ni budućnost",
    "Ljubav je lepa ali slepa",
    "Ljubav je puna meda i jeda",
    "Ljubav ne traje dugo ako ukloniš svađe.",
    "Ljubav nema godina: ona se uvek rađa",
    "Ljubav pametnog zaluđuje",
    "Ljubav prema istini je glavna i najvažnija crta karaktera. Onaj koji laže - nema karaktera",
    "Ljubav prema otadžbini ne zna za tuđe granice",
    "Ljubavna čarolija u pogledu tvom, ti si sreću donijela srcu slomljenom",
    "Ljubazan ali jedva čeka da mu vidi leđa",
    "Ljubi bližnjega svoga kao samoga sebe",
    "Ljudi se najviše muče zbog hleba i ljubavi.",
    "Ljudi se po odjelu sretaju, a po pameti prate.",
    "Ljudi su gusto posijani, ali rijetko niču.",
    "Ljut čovek ne zadrži prijatelja",
    "Magarac - magarac i pod zlatnim sedlom.",
    "Mala sjekira veliki dub povali.",
    "Malena je tica prepelica, al umori konja i junaka.",
    "Mali Hodža, ispod velikog turbana.",
    "Mačija igračka - mišija smrt.",
    "Među ćoravijem, ko ima jedno oko meću ga za Cara.",
    "Mi o vuku, a vuk na vrata",
    "Mlado se drvo savija",
    "Mladost – radost",
    "Mlati rukom, ko kobila repom",
    "Mnogi ljudi su kao satovi: pokazuju jedno vreme, a otkucavaju drugo.",
    "Mnogo asova treba dok se istina sahrani.",
    "Mnogo znati, znači pre vremena ostariti.",
    "Mnogo zrna gomilu načine.",
    "Mnogo je mački celo pečenje.",
    "Mnogo treba vremena da od deteta čovek bude",
    "Mrav i pčela uče kako se teče",
    "Mrtvu kurjaku rep mjeri.",
    "Muka ide po ljud`ma",
    "Mučno je mudrome među budalama besjediti",
    "Muči đeca kad stariji govore.",
    "Na jednu glavu ne može se dve kape.",
    "Na jeziku med, a u srcu jed.",
    "Na kurjake vika, a lisice meso jedu.",
    "Na mlađima svijet ostaje.",
    "Na muci se poznaju junaci",
    "Na poruke vuk mesa ne ije.",
    "Na psa koji bježi svako viče",
    "Na silu se ne može voleti.",
    "Na sirotnoga svakom je laka ruka.",
    "Na sokolu je malo mesa.",
    "Na tuđim leđima lako je breme",
    "Na ugašenu vatru vode ne sipaj",
    "Na usamljenost osuđuju prijatelji.",
    "Navalio ko zima na gola čovjeka.",
    "Navika je jedna muka al odvika dvije.",
    "Navika je jedna muka, a odvika dvije muke",
    "Nad silom sila je pravda.",
    "Naduri se ko ćuran na bunjištu.",
    "Najviše se vole ljudi koji imaju iste vrline, najviše se mrze koji imaju iste mane.",
    "Najgore je kad padneš u njenim očima.",
    "Najpre ispred svoje kuće počisti.",
    "Najčešće opeče potajni žar.",
    "Nalik gajde na muziku",
    "Namrgodio se kao da će mu kiša iz čela udariti.",
    "Napao ko smrt na život.",
    "Ne boj se onoga kome nisi dobro učinio.",
    "Ne bojim se smrti nego zla života",
    "Ne budi otrov da truješ drugog i ne budi med da te drugi poližu.",
    "Ne valja donde leteti dokle krila ne narastu",
    "Ne valja jarca za baštovana namestiti",
    "Ne valja svakoj tici kobac biti.",
    "Ne viči, ono što te je snašlo nećes tako oterati.",
    "Ne vjeruj prijatelju za trpezom, nego na vratima od tamnice",
    "Ne goji se prase uoči Božića",
    "Ne gori nam pod noktima",
    "Ne gori obraz od sunca, već od poštenih ljudi",
    "Ne gori ti pod nogama",
    "Ne guraj nos u tuđa posla",
    "Ne da se posranom do potoka",
    "Ne da se, ali će se dati. [[Vuk Karadžić]]",
    "Ne zna da besjedi, a ne ume da ćuti.",
    "Ne zaboravljaj na smrt, i ona tebe ne zaboravlja.",
    "Ne jedu vuci meso po poruci.",
    "Ne kupuje se sloboda na vašaru",
    "Ne laje kuja radi sela, nego radi sebe.",
    "Ne lipši magarče do zelene trave",
    "Ne može se kriva Drina ramenom ispraviti",
    "Ne možeš dlanom sunce zakloniti.",
    "Ne niče sve što se seje",
    "Ne pada snijeg da pomori svijet, već da svaka zvjerka svoj trag pokaže.",
    "Ne plaši vuka s' kozijom mješinom.",
    "Ne sveti se zlotvoru, no čekaj na Boga.",
    "Ne stoji kuća na zemlji, nego na ženi.",
    "Ne treba kvocati, nego jaja nositi.",
    "Ne trči, ko ždrebe, pred rudu.",
    "Ne hvataj se u kolo ako ne znaš igrati.",
    "Nevolja svačemu čoveka nauči",
    "Neko se za list sakrije, nekoga ni dub da pokrije.",
    "Nekom i olovo plivje, a nekome i slamka tone.",
    "Nema većeg zla, od zle pameti.",
    "Nema zime dok ne padne inje.",
    "Nema leta dok se ne zakikoće lug.",
    "Nema ništa nesnosnije od bogate žene.",
    "Nema tu ćuka, da nije vuka.",
    "Nemirna savest je i tužilac i sudija u isto vreme.",
    "Nemogoše pojedoše, a nekće se sve popiše.",
    "Nemoj, pa se neboj.",
    "Nepostojan kao Mart mjesec.",
    "Nepravdu ne vole ni oni koji ju čine.",
    "Nesta blaga, nesta prijatelja.",
    "Neće kruška ispod trešnje.",
    "Neće kuče na kuče.",
    "Ni vratiša ni platiša.",
    "Ni najbolji petao ne može da izmeni vreme.",
    "Nije vuk ničije sreće izio.",
    "Nije dopušteno sve znati.",
    "Nije žita bez kukolja ni naroda bez izroda.",
    "Nije zlato sve što sija.",
    "Nije nikakva majstorija među dobrima dobar biti.",
    "Nije svaka muka dovijeka.",
    "Nije siromah ko malo ima, već ko mnogo želi.",
    "Nije umrla baba od korbe, već od prazne torbe.",
    "Nije čovjeku žao na malo nego na nepravo",
    "Nijedna muka nije dovijeka.",
    "Nijedno zlo ne prođe neopaženo",
    "Nikad zao na gorega neće.",
    "Niko ne zna šta je dobro, samo onaj koji se zla napatio",
    "Niko ne može natkati mahrama da cijelom svijetu usta poveže.",
    "Niko ne može tako malo da me plati, koliko malo ja mogu da radim.",
    "Niko ne može cijelom svijetu kolača namijesiti",
    "Niko ne ume da se veseli kao sirotinja.",
    "Niko nije zadovoljan svojim bogatstvom i nezadovoljan",
    "Niko sam sebi sudija ne može biti",
    "Niko se nije naučen rodio",
    "Niče đe ga ne siju",
    "Ništa nije lepše od osmeha zaljubljene žene.",
    "Ništa nije tako loše da ne može biti gore.",
    "Nov bunar kopaj, u star ne pljuj.",
    "Nove čizme i nova gospoda najvećma tište",
    "Novci kad odlaze imaju sto nogu, kad dolaze samo dvije.",
    "Novci sitno zveče, al' se daleko čuju.",
    "Nužda nauči i babu igrati.",
    "Njegovo jajce nema žumance.",
    "Njegovo je svako dvožučno.",
    "Njemu i voda uzbrdo teče.",
    "Njemu i jare i pare, a tebi brabonjci (izmet ovce).",
    "Njiva traži radnika a žena neradnika (odmorna čoveka).",
    "Njiva hoće motiku, a ne molitvu.",
    "Njega može da voli samo rođena majka.",
    "Njega ni metak neće.",
    "Njega se ni vrapci ne boje.",
    "Njegova je reč i prva i poslednja.",
    "Njegova kokoška vredi više nego nečiji soko.",
    "Njegova se poštuje.",
    "Njemu i Bog gleda kroz prste.",
    "Njemu ni kesu ni iz kese.",
    "Njima je obraz iza leđa.",
    "O jarane, bole li te rane?",
    "O neprijatelju ne govori zlo, nego misli.",
    "Obećanje, ludom radovanje",
    "Obilazi ko kiša oko Kragujevca.",
    "Običan život je jači od mudrih knjiga.",
    "Oboje je zlo: i svima verovati, i nikome.",
    "Ovca je vučije štene dojila i uzgojila.",
    "Od govneta pita ne biva.",
    "Od zla gore, a od dobra bolje ima",
    "Od inata nema goreg zanata",
    "Od lopova je sigurno što ne dosegne",
    "Od male iskre velika vatra",
    "Od mira glava ne boli",
    "Od pruta biva veliko drvo.",
    "Od samoće ništa gore nema.",
    "Od Svetog Ilije, sunce sve milije.",
    "Ozbiljno odgodimo za sutra.",
    "Onaj ko te se boji kad si prisutan, mrzi te kad si odsutan.",
    "Onaj te voli koji te nagoni na plač.",
    "Onome, ko ume da čeka, vremenom sve dolazi.",
    "Oparen kašu hladi",
    "Osmehni se svakome jutru.",
    "Osoba kojoj \"treba\" ljubav poslednja je koja će je dobiti.",
    "Ostavimo vremenu i našoj rešenosti.",
    "Oteto - prokleto.",
    "Otišao da mu vide noge put",
    "Otkud sam se nadao da me sunce ogrije, otuda me led bije.",
    "Oštar nož ljuto seče, a oštar jezik i gore.",
    "Pametan lako ide, a brzo dođe",
    "Pametna glava - stotinu ruku.",
    "Pametni ljudi uče se na tuđim greškama, budale na vlastitim.",
    "Pijana glava ne nosi barjaka.",
    "Po glasu ptica, a po šapama se lav poznaje",
    "Po drugi put lisicu ne uhvati u gvožđe",
    "Podnosi, a ne tuži na ono čemu se ne može izbeći.",
    "Pozajmi rukama, pa traži nogama.",
    "Poklon dušu gubi.",
    "Poklon i okatog zaslepi.",
    "Pomogneš li zlog u zlu, dobićeš ga za neprijatelja.",
    "Pošten manje obeća, nego što učini.",
    "Preko dubokog potoka prelazi poslednji.",
    "Primaš li poklone, prodaješ slobodu.",
    "Pokraj suha drveta i sirovo izgori.",
    "Pop đaku, đak crkvenjaku.",
    "Posle boja kopljem u trnje",
    "Počni! Započeto je pola dela.",
    "Poštenje je ravno sa životom.",
    "Pošto se kola slome, mnogi put kazuju.",
    "Pošto se napiješ vode, ne muti izvor za sobom.",
    "Poštuj, ako hoćeš da si poštovan.",
    "Prav se smije, a kriv se krije.",
    "Pravda ne može ni utonuti ni izgoreti",
    "Prazna vreća uspravno ne može da stoji",
    "Prva je vrlina biti bez mane.",
    "Prvo pojedi svoje pa tuđe.",
    "Preveo ga žednog preko vode",
    "Preko brda vrba mrda na vrh vrbe leži zec",
    "Preko preče naokolo bliže",
    "Prelomiti jezik — ovladati izgovorom, početi govoriti, progovoriti.",
    "Prema guberu se valja pružiti",
    "Prijatelj je najbolja imovina u životu.",
    "Prijatelj se u nevolji poznaje, kao zlato u vatri",
    "Prijatelju i neprijatelju daj uvek dobar savet, jer prijatelj ga prihvata, a neprijatelj ne.",
    "Priča sebi u bradu",
    "Pričaj zidu",
    "Prokleta nek je zemlja u kojoj su psi pušteni a kamenje svezano",
    "Proricala baba da će biti posle kiše blata",
    "Ptica po perju, a čovjek se po besjedi poznaje",
    "Ravnodušnost je najbolji način u brigama.",
    "Radi pa se ne boj gladi.",
    "Rad je najbolja lutrija.",
    "Rano voće brzo trune.",
    "Razdrta vreća ne može se napuniti",
    "Ralo i motika svijet hrane",
    "Ranoranilac i docnolegalac kuću teče",
    "Rat je kao oblak pa nekog orosi, nekog pokvasi",
    "Rat, rak i rad, su tri najgore srpske reči.",
    "Rđa jede gvožđe, a tuga srce.",
    "Rđa ne prijanja za zlato",
    "Rđav je čovek koji se tuđem zlu raduje",
    "Rep glavi ne zapovijeda",
    "Retka je sreća bez gordosti",
    "Reč \"sutra\" je izmišljena za decu i za neodlučne ljude.",
    "Reči su kao pčele, one su istovremeno i med i žaoka.",
    "Reči treba meriti, a ne brojati.",
    "Riba od glave smrdi, a od repa se čisti",
    "Riba ribi grize rep",
    "Riba ribu, a ribar obe",
    "Ribe se love udicom, a ljudi rečima",
    "Rizik stvara kapital",
    "Roba govori, trgovac laje, gazda pare daje",
    "Robija nije teška, već robijaši",
    "Rovitom govnetu malo vode fali(kiše treba)",
    "Rodi me majko srećnog, pa me baci u trnje",
    "Ruga se lonac loncu, a oba su crna",
    "Rugovka je klela: Umro joj sin da bi mogla lošu *snahu da pusti",
    "Ruka koja daje ne oskudeva",
    "Ruka ruku mije obraz obad bije",
    "Rumena zora, mokra gora",
    "S brda s dola",
    "S kim si takav si",
    "S konja na magarca",
    "S pola jezika (reći, kazati) — poluglasno, tiho (reći, kazati)",
    "Sa dva ili tri čoveka još možeš pričati a ljudi su već razuzdana rulja",
    "Sablju paši konja jaši pa u boj se spremaj",
    "Sad smo kvit",
    "Sakrio se u mišiju rupu",
    "Samo vi vršljajte (što bi rekli naši stari),poslje ja moram sve da sravnavam",
    "Samo nek komšiji crkne krava",
    "Sačuvaj se Bože, od mirnog sina kod opake snaje.",
    "Sva je huka na vuka, a iza vuka i lisica sita",
    "Sva mu je pamet na jeziku. Ko govori šta mu na usta dođe",
    "Svagđe je dobro, ali kod kuće je najbolje.",
    "Svak za se koze pase!",
    "Svak po sebi sudi o drugome.",
    "Svaka batina ima dva kraja",
    "Svaka budala ima svoje veselje",
    "Svaka žurba je spora",
    "Svaka je šala pola istine",
    "Svaka knjiga ima svoju sudbinu.",
    "Svaka muka za vremena, a sramota zavijeka",
    "Svaka ptica svome jatu leti",
    "Svaka kamena glava, jednim udarcem čekića se razbija",
    "Svaki je početak težak",
    "Svako ima prava koliko ima moći.",
    "Svako je svoje sreće kovač",
    "Svako čudo za tri dana",
    "Sveća je sveća ako je slepac i ne vidi",
    "Svojstvo je ludosti tuđe mane videti, a svoje zaboraviti.",
    "Svuda pođi, kući dođi.",
    "Sirotinjo, i Bogu si teška",
    "Sit gladnom ne veruje",
    "Slabo slovi, ali dobro lovi.",
    "Sloboda je, ne da radiš šta hoćeš, već da ne radiš, šta nećeš.",
    "Slogom rastu male stvari, neslogom se i najveće raspadaju.",
    "Slađa je i milosna reč, nego nemilosna milostinja.",
    "Spolja je gladac, a iznutra jadac",
    "Spram sveca i tropar, spram andjela i krila",
    "Snaga na usta ulazi",
    "Srećan je onaj koji sedi u svojoj kući",
    "Srce oće, a dupe klokoće",
    "Srditom popu prazni bisazi.",
    "Srebrno sedlo ne čini dobra konja",
    "Sreća se sastoji od izbegnutih nesreća.",
    "Srećan je onaj koji sedi u svojoj kući.",
    "Stari vuk, pasja sprdačina.",
    "Starije je jutro od večeri.",
    "Starci bolje na daleko vide.",
    "Starost je bolest od koje svako umire.",
    "Sto ljudi, sto ćudi.",
    "Strah je već pola nesreće.",
    "Strpljenja! Vremenom od trave postaje mleko.",
    "Takav je čovek, samo onima najviše zavidi kojima najviše duguje.",
    "Tvrd je orah voćka čudnovata, ne slomi je al zube polomi.",
    "Tamnica je za ljude načinjena",
    "Terao zeca pa isterao vuka",
    "Teško volu u jarmu i čoveku u najmu.",
    "Teško domu u kom nema sloge",
    "Teško zemlji kuda prođe vojska",
    "Teško je dobro videti, a lasno ga poznati ",
    "Teško je dugo dobar biti",
    "Teško je čuvati tuđe pare i svoju ženu.",
    "Teško je šutu sa rogatim bosti se",
    "Teško konju kog slepci teraju",
    "Teško nogama pod ludom glavom",
    "Teško onome koji neprijatelja na kućnom pragu čeka",
    "Teško onome koji ne zna, a učiti se ne da.",
    "Teško svetu kad se lude pojunače",
    "Teško svuda svome bez svojega",
    "Teško tome ko za tuđom pameti ide",
    "Tiha voda brijeg roni.",
    "Traži hljeba preko pogače",
    "Triput kroji, jedanput reži.",
    "Tuđa ruka svrab ne češe.",
    "Tuđe je sve lijepo, ali je svoje najljepše.",
    "Tuđe je slađe.",
    "Tuđina je svuđe ista.",
    "Tuđoj se budalaštini smejemo, a svoje se ne stidimo",
    "Tukle se jetrve preko svekrve.",
    "Tumara ko pijan po pomračini.",
    "Tup kao ud.",
    "Tup ko budak. ",
    "Tucao mu luk na glavi",
    "Ćeraćemo se mi još",
    "Ćirilica nema ćelava, a latinica imade",
    "Ćutanje zlata vredi",
    "Ćutanje je zlato",
    "Ćuti avetinjo jedna",
    "Ćuti i pokri se ušima",
    "Ćuti kao prase kad piša u vodu (iz Šumadije)",
    "Ćuti, tu si gde(di) si",
    "Ćorava mu posla!",
    "Ćuti, da ne urekne zlo!",
    "Ćuti, dobro nije!",
    "Ćuti i gledaj svoja posla.",
    "Ćuti ko govedo.",
    "Ćuti ko kurva.",
    "Ćuti ko mula.",
    "Ćuti ko ćutuk.",
    "Ćuti i plivaj dalje!",
    "Ćutanje je zlato a govorenje srebro.",
    "Ćorava mu sreća.",
    "Ćar poeo vajdu.",
    "U vinu je istina.",
    "U gladnim očima svaki je komad mali.",
    "U kog je nož, u tog je pogača",
    "U kog su ovce, u tog je i planina",
    "U koga je pogača u toga je i nož",
    "U kolo kad hoćeš, iz kola kad puste.",
    "U nevolji ne treba plakati, nego leka tražiti",
    "U ratara crne ruke, a bijela pogača",
    "U sreću se uzda lud, a pametan u svoj trud",
    "U stara glava, u mlada snaga",
    "U stara krvnika nema novog prijatelja",
    "U tekućoj vodi mulj ne leži",
    "U tuđem oku vidi slamku, a u svome grede ne vidi",
    "U šumu drva nosi",
    "Uz malo može biti dosta, a u dosta malo",
    "Uzeh vraga radi blaga; blago nestade, a vrag ostade",
    "Um caruje, a snaga klade valja",
    "Umro ko radi, umro ko ne radi",
    "Utopljenik se za slamku hvata",
    "Uzdaj se u se i u svoje kljuse",
    "Učenje je svetlost.",
    "Učiniš li zlo, ne misli da će te zlo mimoići.",
    "Učini dobro, ne kaj se; učini zlo, nadaj se.",
    "Fale mu dva kraja i sredina.",
    "Falim te Bože!",
    "Fali mu jedna daska u glavi.",
    "Frkće ko pokiso konj.",
    "Fabrika je košnica sa mnogo trutova",
    "Fali mi pet da načinim šest",
    "Fali mu daska u glavi",
    "Fudbal vode pametni, a gledaju ludi",
    "Fudbal se ne igra za publiku nego za novac",
    "Frkće od besa.",
    "Hajduke narod ceni, ali za njima u goru neće",
    "Hajdučke kuće nema",
    "Hartija i ćuprija trpe sve",
    "Hvali ga ko Ciganin konja",
    "Hvali selo, a živi u gradu",
    "Hvalte me usta da vas ne pocepam(poderem)",
    "Hvala ti do neba!",
    "Hvala ti ko bratu!",
    "Hvalim te Bože!",
    "Hvali se ko Crnogorac.",
    "Hvaliti na sva usta.",
    "Hvata zmije tuđim rukama.",
    "Hvata muvu na sirće.",
    "Hvata se u kolo, a ne ume da igra",
    "Hladan ko stena.",
    "Hladan ko špricer.",
    "Hleba i igara, pisaru.",
    "Hlebom ga dušmani hranili!",
    "Hoće vatru koja ne peče.",
    "Heroj nadživi sebe",
    "Hleb jesti - nije majstorija; hleb peći - mala je majstorija; a hleb zaraditi - to je najveća majstorija",
    "Hoćeš li da te svi mrze, reci svakome ko je ko.",
    "Hranitelj je kao i roditelj",
    "Hoće ga svaki đavo.",
    "Hoće hleba preko pogače.",
    "Hoće hleba bez motike.",
    "Hrabrima sreća dodaje ruku.",
    "Hrabrom i sreća pomaže.",
    "Hrabre sreća prati!",
    "Car nad carom uvek se nađe",
    "Carska se ne poriče",
    "Caru carevo a bogu božje navjek i amin",
    "Cvet je najlepši dok je neubran.",
    "Crnogorci ne ljube lance",
    "Celom svetu ne možeš ugoditi!",
    "Cigani ti kuću kućili!",
    "Caru carevo, nama naše.",
    "Crn mu obraz!",
    "Crno rade a još crnje misle.",
    "Celo leto jedna šljiva, i ona crvljiva.",
    "Car daleko, a Bog visoko.",
    "Časna smrt proslavi vas život.",
    "Čaša iza čaše, a iza čaše istina.",
    "Čega se mudar stidi, tim se lud ponosi.",
    "Čega je srce puno, toga i jezik.",
    "Čelo, oči i pogled vrlo često lažu, a govor najčešće.",
    "Često malena varnica veliku vatru užeže",
    "Četiri stvari mogu da unište čoveka: rđava zemlja, zla žena, loš porod i mrtav kapital.",
    "Čija sila, toga i pravda.",
    "Čije june, onoga i uže",
    "Čini dobro, dobrome se nadaj, čini loše, još gorem se nadaj.",
    "Čini dobro, raduj se, čini loše, nadaj se.",
    "Čini drugom što je tebi drago da ti se učini.",
    "Čist račun, duga ljubav",
    "Čisti računi - dobri prijatelji.",
    "Čistoća je pola zdravlja",
    "Čovek bez slobode, k’o riba bez vode",
    "Čovek želi da je od svakoga bolji, a od sina da je gori.",
    "Čovek ima samo ono što daje.",
    "Čovek je tvrđi od kamena, a slabiji od jajeta.",
    "Čovek se do smrti uči",
    "Čovek se nada dok god je duše u njemu",
    "Čovek se pozna u tri slučaja: u jelu, u bogatstvu i u pijanstvu.",
    "Čovek se prima prema odelu koje nosi a ispraća prema duhu.",
    "Čovek se uči dok je živ, pa opet lud umre.",
    "Čovjek sve dava za obraz, a obraz ni za šta",
    "Čuvaj bele novce za crne dane.",
    "Čuvaj se mnogih ako se ne bojiš pojedinaca.",
    "Čuvaj se onih koji kroz smeh ujedaju.",
    "Čuvaj se onoga ko stavlja obraz pod opanak.",
    "Čuvaj se tihe vode i psa koji ćuti.",
    "Čuturom se pregrabi i najveće bure",
    "Džaba ti svila i kadifa.",
    "Džabe je i sirće slatko.",
    "Džabe mu je, da dubi na glavi.",
    "Džin na staklenim nogama.",
    "Džak soli treba pojesti sa čovekom, da bi ga dobro upoznao.",
    "Džaba ga bilo!",
    "Džaba ti supa kad je slana.",
    "Džaba im.",
    "Šeta se po oštrici noža",
    "Šilo za ognjilo",
    "Šolju mleka pa u krevet",
    "Šta vredi znanje bez radnje",
    "Šta zna dete šta je petsto kila - uze i odnese.",
    "Šta ko misli, o onom i sanja.",
    "Šta ko čini sve sebi čini.",
    "Šta me gledaš, ko da igra bela mečka",
    "Šta osveta čini",
    "Što se hoće to se može.",
    "Što više sile, više i zla.",
    "Što više ljubavi vraćaš, više ćeš i primiti.",
    "Što danas ne potrošiš, to si stekao.",
    "Što ih manje titraš to te više spopadaju",
    "Što ih pasa laje, da svaki ujede, zlo",
    "Što je babi milo to joj se i snilo",
    "Što je brzo to je kuso",
    "Što je veća ptica, veće joj gnezdo treba",
    "Što je više brdo, to je dublja dolja.",
    "Što je život skuplji - karakter je jeftiniji.",
    "Što je svačije, to je ničije.",
    "Što jedan lud zamrsi, sto mudrijeh ne mogu razmrsiti",
    "Što ljudi imaju više, to više žele.",
    "Što ne znaš pitaj onoga ko zna.",
    "Što ne umeš popraviti, nemoj ni menjati.",
    "Što ne ide od srca, ne ide ni k srcu.",
    "Što nećeš nekome u oči da kažeš, nemoj govoriti ni za leđima.",
    "Što si rad da sam znaš, ne govori nikom.",
    "Što smije pop, ne smije đak.",
    "Što srce ne zapazi to ni oči ne vide.",
    "Što ti je život - tražiš od pravde ruku, dobiješ nogu.",
    "Što ti je suđeno doći će ti i preko plota.",
    "Što ti meni popuješ.",
    "Što trijezan misli, (to) pijan govori.",
    "Što u kući treba, crkvi se ne daje.",
    "Što čovek više živi, više i zna",
    "Što čovek manje zna to mu se njegovo znanje čini obimnije",
    "Šuga i ljubav se ne mogu sakriti",
    "Šugava ovca sve stado ošuga.",
    "Šuplju glavu i vetar nosi.",

    "Para vrti tamo gde burgija neće."
];

const akcija = [
    "",
    "\n*Voli*",
    "\n*Žmirka*",
    "\n*Odmeri te*",
    "\n*Počeše dupe*",
    "\n*Počeše muda*",
    "\n*Merka te*",
    "\n*Merka te pa počeše guzicu*",
    "\n*Merka te pa počeše muda*",
    "\n*Voli*",
    "\n*Prdne*",
    "\n*Podrigne*",
    "\n*Podrigne pa prdne*",
    "\n*Podrigne, prdne pa se počeše za dupe*",
    "\n*Podrigne pa se počeše za dupe*",
    "\n*Prdne pa se počeše za dupe*",
    "\n*Prdne pa se okrene da pomiriše*",
    "\n*Počeše se po glavi*",
    "\n*Usere se*",
    "\n*Upiša se*",
    "\n*Ode da kenja*",
    "\n*Ode da piša*",
    "\n*Vrati se da rani stoku*",
    "\n*Krene da se dere Dragici*",
    "\n*Pljune*",
    "\n*Pljune te*",
    "\n*Pljune Zokija*",
    "\n*Pljune Dragicu*",
    "\n*Pljune Zokiju u dvorište*",
    "\n*Pljune Dragicu*",
    "\n*Vrati se parenju svinja*",
    "\n*Vrati se parenju stoke*",
    "\n*Krene da muze kravu u vazduhu*",
    "\n*Namigne*",
    "\n*Namigne pa prdne*",
    "\n*Namigne pa se usere*",
    "\n*Namigne pa te šutne*",
    "\n*Šutne te*",
    "\n*Krene da igra kolo*",
    "\n*Krene da peva himnu*",
    "\n*Krene da peva narodno*",
    "\n*Krene da plače*",
    "\n*Krene da plače i zove kafanu*",
    "\n*Krene da plače i zove Dragicu*",
    "\n*Krene da plače i zove Zokija*",
    "\n*Krene da plače i zove Tita*",
    "\n*Seti se Tita*",
    "\n*Ode da spava*",
    "\n*Ode da spava na klupi*",
    "\n*Pozove komšije*",
    "\n*Pozove miliciju*",
    "\n*Izvadi ga*",
    "\n*Izvadi revolver*",
    "\n*Izvadi štek sa devize*",
    "\n*Izvadi 100e*",
    "\n*Izvadi 200e*",
    "\n*Izvadi 500e*",
    "\n*Izvadi 1000e*",
    "\n*Zapali cigaru*",
    "\n*Zapali tompus*",
    "\n*Zapali džoint*",
    "\n*Psuje dugove*",
    "\n*Psuje dušmane*",
    "\n*Čačka nos*",
    "\n*Čačka nos pa te gađa slinom*",
    "\n*Čačka nos pa zalepi slinu od majcu*",
    "\n*Čačka nos pa zagleđuje slinu*",
    "\n*Čačka uvo*",
    "\n*Čačka uvo pa zagleđuje mastan prst*",
    "\n*Šmrke*",
    "\n*Šmrke, nakašlje se, pljune*",
    "\n*Nakašlje se, pljune*",
    "\n*Izbaci šlajm*",
    "\n*Uvuče šlajm*",
    "\n*Kine*",
    "\n*Kine i prdne u isto vreme*",
    "\n*Cokće*",
    "\n*Nasmeje se*"
];

const image = [
    "https://drive.google.com/uc?export=view&id=13vj8C9zqsTzQXILPRb-i3Wv-E9Dewyo4",
    "https://drive.google.com/uc?export=view&id=1BlZY66hFpDi-FEAuuYloFTJDqjz6ZK8d",
    "https://drive.google.com/uc?export=view&id=1pjtm8cA2FnMnymXvsAr-wcvfBE2utIkY",
    "https://drive.google.com/uc?export=view&id=14hP7_RqeUhJTF-fSSJ54SS1ngphdsBsP",
    "https://drive.google.com/uc?export=view&id=1XXu0ZiT5d7cDTMaTXHeOIfdnbFES6Wtx",
    "https://drive.google.com/uc?export=view&id=1Q5e9V0riVov0ln7BYNFDWB-PhhzjUPuA"
];

module.exports = {
    poslovica,
    akcija,
    image
};