const exercises = [
    "jumping jacks",
    "high knees",
    "side-to-side chops - like swinging an axe!",
    "squats",
    "lunges",
    "elbow plank",
    "push-up plank",
    "mountain climbers",
    "plank jump-ins: plank, jump feet up to hands, then jump back out to plank",
    "push-ups",
    "reverse lunges",
    "standing side shoulder taps: arms in a palms-up T, then touch shoulders, back out",
    "bicep extensions: fists palm up out in front of you, curl in toward chin, back out",
    "hop heel clicks: hop and touch hand to opposite heel, hop and do the other",
    "march steps",
    "one leg balance hold - 30 seconds each side",
    "warrior pose hold - 30 seconds each side",
    "one leg plank hold on elbows - 30 seconds each side",
    "one leg plank hold on hands - 30 seconds each side",
    "calf raises",
    "calf raise hold",
    "side leg raises",
    "torso twists",
    "lunge step ups: lunge then stand and bring knee up to hip-height",
    "punches",
    "side bends",
    "side jacks: one side jumping jacks at a time, stepped out like a lunge",
    "step jacks: do a jumping jack but step out one leg at a time",
    "opposite knee to elbow: like standing cross-crunches",
    "jumping lunges",
    "side-to-side lunges",
    "shoulder taps in push-up pose",
    "burpees",
    "flutter kicks on back",
    "side to side heel taps on back: lay on your back with bent knees, lift head and chest up a bit, rotate to tap heels one at a time",
    "squat hold with punches",
    "squat hold",
    "butt kickers",
    "split jacks front to back: like lunges, but swing your opposite arm up in front of you while you do it, jumping from one to the other",
    "leg swings front to back",
    "leg swings out to the side",
    "plank walk outs",
    "arm raises: from a T to goalposts",
    "chest expansions: from T to candlesticks",
    "overhead punches: punch God!",
    "uppercuts",
    "hook punches",
    "mountain climber taps: instead of jumping, just bring a knee up and tap your heel with your hand",
    "plank thigh taps: plank in a push-up pose, and lift one hand off the ground to press against your side at a time",
    "up and down planks: alternate from push-up pose to elbow planks",
    "jumping T's '('jumping jacks with arms only coming out to a T pose')'",
    "seal jacks '('jumping jacks with hands clapping out front and then out to the sides in a T')'",
    "seated leg raises, one at a time",
    "seated leg raises, both legs together",
    "seated leg swings, one leg at a time, pump leg up and down keep it straight, 30 seconds each side",
    "back leg raises",
    "forward bend: bend at waist like a table top and then return to standing",
    "arm raises: from resting at sides to candle sticks",
    "arm scissors",
    "up and down shoulder taps: raise hands to the heavens, tap shoulders, repeat",
    "donkey kicks: get in doggy style pose, kick leg straight out backwards",
    "doggy leg swings: get in doggy style pose, stretch leg out backwards, pump up and down, 30 seconds each side",
    "doggy side leg extensions: like a dog peeing on a fire extinguisher over and over again",
    "glute flexes: lay on stomach and elbows, make froggy legs with your feet up in the air, lift thighs off the ground",
    "glute flex hold: lay on stomach and elbows, make froggy legs with feet up in the air, lift thighs off the ground and hold",
    "clamshells: lay comfortably on side, legs bent, open and close one bent leg, 30 seconds each side",
    "v leg extensions: lay on back with legs straight up in the air, spread them out to a V, then close them again",
    "balance holds: stand on one leg then bend forward at waist, putting your other leg straight back and the opposite arm straight forward, and hold 30 seconds each side",
    "balances: stand on one leg, then bend forward at waist, putting other leg straight back and opposite arm straight forward",
    "cow and cats: doggy pose, dip back down and lean head back, curl forward like an angry cat, repeat",
    "doggy balances: doggy pose, stretch opposite arm and leg forward and backward, switch and repeat",
    "childs pose to upward dog and back again",
    "arm cicles out to the side",
    "arm circles in front",
    "march and pump arms up and down out to the side",
    "supermans: lay on stomach with chest and feet off the floor, lift to the ceiling and rest down",
    "reverse flutter kicks: lay on stomach with legs off the ground, flutter them up and down",
    "knee rolls: lay on back with bent knees together, roll them to one side then the other",
    "punch, punch, squat",
    "W extensions: lay on stomach with legs straight and chest off the ground. put hands by ears and then push them forward and back",
    "prone reverse fly: lay on stomach, legs straight, chest off ground. Put palms on the ground out to the sides and then lift them up",
    "reverse angels: lay on stomach, legs straight, chest off ground. arms go from straight out in front down to the hips and back up",
    "swimmers: lay on stomach, legs straight and off the ground, chest up, arms out forward, and swim legs and arms up and down",
    "sit-to-stand: stand in front of a chair, sit back until you touch your butt, then stand back up",
    "hip rotations: stand up and point hips from side to side",
    "side bends, arms up",
    "squat hold side bends",
    "half jacks: jumping jacks, no arms",
    "hop heel clicks: jump and click your heels together",
    "raised leg push-ups",
    "squat step backs: squat and when you come up, step your leg crossed behind your other",
    "goblet squats: squat then come up to a calf raise, arms bending under your chin when you squat and straight back down to your sides when you raise",
    "squat to front kick",
    "squat hold calf raise: squat down and hold it, going up on your toe one side at a time without lifting out of the squat",
    "tricep dips",
    "tricep dip hold",
    "plank rotations: do a plank, raising one arm at a time up to the sky by rotating your body from side to side",
    "side bridge: hold a plank on one elbow facing sideways",
    "plank rolls: plank but rotate hips side to side to touch floor",
    "seagulls: plank, moving one arm at a time in a swimming motion from front to side",
    "plank crunches: plank, curling one knee up to the side at a time toward elbow",
    "crunch kick: lay on back, up on your elbows, holding legs off the ground with bent legs, then kick them forward together and back in",
    "bridge taps: lay on back, knees bent. Lift butt off the ground and thrust hips up toward the ceiling, at the same time, rotate and tap your hand to the ground on the opposite side of your head.",
    "bridges: lay on back with bent knees, then thrust hips up to the ceiling",
    "bridge hold: lay on back with bent knees, hips up off the ground, hold",
    "scissor chops: chop hands up and down straight out in front of you",
    "side kicks: do one side for 30 seconds, then the other",
    "side-to-side kicks: side kicks, alternate legs",
    "front, side, back leg raises, one leg all the way through at a time",
    "front, side, back leg raises, doing both fronts, both sides, then both backs to alternate feet",
    "jump squats",
    "knee strikes: imagine you're twisting to knee an opponent in the guts",
    "palm strikes",
    "bounce in place, like you're jumproping",
    "pacer steps: stand like you're prepping for a cheer stunt as a base, then bounce from foot to foot quickly",
    "crunches",
    "oblique crunches",
    "bicycles",
    "leg scissors: lay on back, head up, legs off the ground out straight, and scissor them",
    "laying leg raises: lay on back, head up, legs off the ground, lift up to 90 degrees and then back down",
    "russian twists",
    "laying flutter kicks: lay on back, head up, legs off the ground, flutter legs",
    "laying 6-12s: lay on back, head up, legs off the ground 6 inches off the ground, hold for 5, raise to 12 inches off the ground, hold for 5, repeat",
    "v extensions: balance on your butt, then extend arms up and legs forward and pull back in, trying to hold balance",
    "butt balance hold: balance on butt, keep legs bent and feet just barely off the ground, arms out straight and hold",
    "v-ups: lay on back with arms over head, sit up and do a toe touch out to the sides",
    "side to side hops: hop from one foot to the other",
    "seated leg twists: sit in a chair, put legs out forward, then curl them in with a twist to the side, repeat",
    "plank alternate arm and leg raises",
    "side to side deep lunges, butt to heel",
    "single-leg bridges: lay on back with one knee bent and one leg up, lift hips",
    "single-leg bridge hold: lay on back with one knee bent and one leg up, lift hips and hold 30 seconds per side",
    "windshield wipers: lay on back with legs up at 90 degrees, move them side to side like windshield wipers, going as low as you can",
    "jump tucks",
    "side to side jumps: jump with both feet from side to side like a slalom skiier",
    "skip, jumping up as high as you can",
    "lunge with a twist: lunge and turn your body side to side",
    "balance side lunges: lunge, then pick leg up when you return up to center to balance for a moment before switching",
    "knight steps: stand, lunge forward, pull back leg forward so you're on both knees, step up to the opposite side lunge, then stand, repeat",
    "elbow clicks: arms out to the side, bent at 90 degrees with your fists up, fold them together in front so your forearms touch in front of your face",
    "scorpion twists: lay on stomach with one leg back straight and the other up in the air with the knee slightly bent. Twist so that foot in the air touches the ground on the opposite side of the body",
    "hold tree pose, 30 seconds each side",
    "sitting punches: sit with legs slight bent out in front of your, lean back a bit and punch, rotating from side to side as you do",
    "arms up bridges: lay back, knees bent, arms stretched up over head, then lift hips off the ground again and again",
    "sit-ups",
    "jab-cross: forward punch, then a twist punch from the other side",
    "jab-hook",
    "jab-jab-hook",
    "jab-hook-uppercut",
    "side plank crunches: push-up pose with one hand, facing the side, then do oblique crunches down while bringing the bottom knee up",
    "bent over rows: get weights, bend knees a bit, bend forward like a table-top, and then hold weights down by shins, pulling up to your chest",
    "weighted side bend: hold a weight in each hand, then bend side to side",
    "weighted bicep curls",
    "weighted squats",
    "weighted deadlifts: bend forward like table top with knees bent until weights touch the floor, then stand up so weights are in front of your hips",
    "arms out one-leg deep squats: arms out like a tee, one leg held out forwrd, then squat all the way down and all the way up on the other leg",
    "squat-jab-jab",
    "5 bounces-1 squat",
    "squat-jab-cross",
    "updog to downdog",
    "knee-in extensions: do downward dog with one leg up as high as you can in the air behind you, then curl that knee into your chest and let your back arch, then kick it back out",
    "laying side leg raises: lay comfortably on side, lifting leg up in the air, 30 seconds each side",
    "weighted upright rows: hold weights down by hips, then pull them up to your chin with your elbows out to the sides",
    "weighted shoulder press: weights in front of collarbones, then press up",
    "weighted tricep extensions: hold weight behind head, lift straight up, one hand at a time,",
    "weighte tricep extension, both hands: hold weights together behind head, lift up",
    "lunge to front kick",
    "high squats: squat with arms straight up",
    "cross-body push-up: when you go down for your push-up, twist so your hip hits the floor and your knee pushes through to the other side",
    "push-up plank hold at bottom. Do a push-up down to the floor, and hold it at the bottom",
    "side-kick hold: kick out to the side and hold for 10 count",
    "seated leg raise hold: sit down and lean back on hands, one knee bent, lift the other straight leg off the ground, and hold",
    "side plank one-leg hold: do a side elbow plank, lift one leg up, hold",
    "single leg hops: 30 seconds each side",
    "weighted renegade rows: do push-up positions on weights, lift one weight up to your chest, then the other",
    "weighted squat into shoulder press",
    "bear crawl: do downdog, but crawl around like that",
    "wall push-up",
    "counter push-up",
    "wall sit",
    "weighted standing twists",
    "weighted alternating shoulder press",
    "shrimp squats: Stand and hold your ankle, then squat until your knee touches the ground",
    "knee in-outs: sit on ground leaned back on hands, hold feet off the ground, and then curl them in with a twist before extending again",
    "clapping push-ups",
    "tuck hold: balance on butt, hold arms around legs in a tuck, and hold",
    "boat pose hold: balance on butt with straight legs, lean back with arms wide open, and balance",
    "tuck sit hold: sit on butt with knees up to chin and feet not touching ground, press palms down on floor, and try to lift butt off ground",
    "hollow hold: lay on back with arms straight up overhead, lift chest and legs off the ground making a hollow shape with your body and hold",
    "front kick-squat-front kick",
    "jab-cross-hook-uppercut",
    "side jackknives: lay on side straight with top hand behind head,  curl and lift everything in a side crunch and lay back down",
    "leaning plank: do a push-up plank but try to have your hands further back down by your hips so your leaning out over your hands",
    "crane pose: plant hands on floor and try to get knees onto elbows",
    "pike push-ups: push-up in downward dog",
    "cross tricep extension pushups: do an elbow plank with your arms crossed folded in front of you, then push-up so you're in a push-up pose with your hands crossed",
    "back lift hold: lay on back with elbows out to each side and fists in the air, then try to lift your back up off the ground so you're held up on your elbows",
    "reverse grip plank: push-up plank, but turn hands so fingers are pointing at feet",
    "fly steps: crouch like you're getting ready to take off in a sprint with hands on the ground, then stand and throw both arms and one leg back",
    "hook kicks: knee comes up straight in front of you before you turn into a side-kick. Try to make it one smooth motion",
    "butt ups: lay on back with legs straight up and hands pressed to floor by hips. Try to lift your butt up off the ground",
    "candlestick hold: lay on back with legs straight up and hands pressed to the floor by hips: lift butt and torso off the ground so you're balanced over your shoulders, using your hands to support your back",
    "hundreds: lay on back with knees at 90 degrees, held off floor, then do crunches with arms held down by your hips",
    "half squat walk: squat down to 90 degrees at the leg, then walk like that",
    "elbow strike sit-ups: sit-ups, but twist and do an elbow strike at the top",
    "deep cross chops: squat, doing an axe chop to the side at the bottom",
    "close-grip push-ups",
    "twist jacks: jump legs back and forth like a shallow lunge, swinging arms from one side to the other",
    "speed skaters",
    "fast tendus in position [random5]",
    "slow tendus in position [random5]",
    "front tendus in position [random5]",
    "side tendus in position [random5]",
    "back tendus in position [random5]",
    "front, side, back, side tendus in position [random5]",
    "front to back ron de jambe in position [random5]",
    "back to front ron de jambe in position [random5]",
    "alternating ron de jambe in position [random5]",
    "plies in position [random5]",
    "fast degages in position [random5]",
    "slow degages in position [random5]",
    "front degages in position [random5]",
    "side degages in position [random5]",
    "back degages in position [random5]",
    "fast ron de jambe in position [random5]",
    "slow ron de jambe in position [random5]",
    "front, side, back, side degages in position [random5]",
    "front fondue in position [random5]",
    "side fondue in position [random5]",
    "back fondue in position [random5]",
    "front, side, back, side fondues in position [random5]",
    "front developpe in position [random5]",
    "side developpe in position [random5]",
    "back developpe in position [random5]",
    "front, side, back, side developpe in position [random5]",
    "fist clench unclench",
    "weighted skull crushers - lay down on back with knees bent and feet on the floor. hold weights together straight up in the air, bend them down toward forehead, and back up",
    "thigh flies - lay on back with arms down by side. lift legs up, open them, then close, repeat",
    "bridge leg lifts - do a bridge, moving leg from pointing down to pointing up and back",
    "laying weighted chest flies - lay on back with knees bent, feet on floor. Hold weights straight up, open arms out to the sides as far as you can, then back up",
    "knee tuck crunches - lay on back, hands under lower back, make a 90 degree angle with feet off the floor, then crunch knees up to your chest and return to the 90 degree angle",
    "cat-cow pose alternation",
    "twisting crunches - crunches with ankle on opposite knee",
    "Fingertip push-ups - get on hands and knees, holding palms off the ground, then do push-ups. Knees can be closer to under hips for this",
    "walk-outs - start in a push-up plank, walk feet with legs remaining straight up until you're doing a toe-touch stretch, then walk hands out back into plank pose, repeat",
    "weighted seated straddle stretch - sit with feet in toe-touch position out to the sides and back straight. Hold a weight over head and slowly twist and lean body toward one foot, repeat to other side",
    "knee leans - get on your knees with the rest of your body straight, hands out in front of you, then lean back with whole body and return to center",
    "elbow plank to downward dog push-ups",
    "heel tap squat hold - squat down a little and hold arms out to sides, twist body to touch your hand down to your heel while the other arm goes up, alternate with a little pulse for momentum in between",
    "speed skater lifts - lunge down to one side with legs spread wide, then return to center and lift the foot you just lunged toward up off the ground to your chest, alternate",
    "couch taps - stand in front of the couch, and run in place, tapping each foot against the couch cushion as you do",
    "tricep dips against couch or chair",
    "tricep dips against couch or chair with one leg raised, 30 seconds each leg",
    "alternating step-ups - get a box or chair, something to stand on, put a foot up on it, stand up and pull the back foot up to your chest before going back down, alternate each rep",
    "one leg step-ups - get a box or chair to stand on, put a foot up on it, stand up and pull the back foot up to your chest, 30 seconds each side at a time",
    "push-up to child's pose, repeat",
    "plank foot taps - plank and tap each foot out to the side, alternating each rep. 30 seconds on hands, 30 seconds on elbows",
    "bridge overhead taps - sit on but with feet on floor braced on arms behind you. Lift hips off the ground, kicking leg straight up and touching toe with opposite hand",
    "upright runners - lay on back with arms down at side, lift a leg up straight and the other straight and held off the ground and switch, essentially doing a straight-leg run in the air",
    "leg and hip lifts - lay on back and do leg lift, push hips up off the ground at the top",
    "foot slides - get in push-up pose with feet on a towel or something slippery. slide feet so knees come up to chest and back down",
    "foot slide push-ups - get in push-up pose with feet on a towel or something slippery. slide feet so knees come up to the chest and back down, then do a push-up",
    "foot slide circles - get in push-up pose with feet on two towels or something slippery. slide feet up toward chest, open them apart as you slide down, then bring together again, drawing opposite cirlces with each foot",
    "arm slide-outs - get on knees with feet lifted off the floor, put hands on a towel, and slide out forward before pulling back in",
    "side V's - lay on side, then jackknife up into a side-V",
    "knee hugs - Lay on back, arms stretched up so you're as long as possible, swing arms up and over and curl knees up to your chest at the same time, like a V-up but with tucked knees instead",
    "leg drops - lay on back with feet straight up in the air and head lifted off ground. Every ten 5 seconds, lower slightly toward the floor, working your way down over the course of a minute",
    "leg circles - lay on your back with hands beneath spine, draw giant circle in the air with both legs together, 30 seconds each direction",
    "starfish crunch - do crunches with one leg straight out on the floor, the other straight up in the air, touching your toe with opposing arm while the other arm is held out to the side, alternating each crunch",
    "side crunch - lay on side, and do oblique crunches",
    "pike shoulder presses - put feet on couch, face down, and bend arms like you're going to do a headstand. Press arms up so your arms are straight and hips end up lifted in the air",
    "staggered push-ups - push-ups with one hand more forward and one hand more backward, alternate",
    "tricep extensions - elbow planks, push up to push-up pose in one fluid motion",
    "wall-squats - wall-sit pose, slide up to standing, lower back down again",
    "door frame row - squat with one arm holding door frame, pull yourself into the doorframe, then settle back so arm is straight, 30 seconds each arm",
    "raised leg crunches - lay on back with feet straight and barely lifted off floor, then do crunches",
    "triangle crunches - on one hand and one knee, facing out sideways, let top leg be straight with toe on the ground, then lift it off for a side crunch",
    "reverse plank kick - get in push-up plank pose, but facing up toward the ceiling so arms are behind you. Kick legs up one at a time",
    "pyramids - stand with one leg more forward than the other so legs make a triangle. press palms together behind your back, bend forward at the waist as much as you can for a stretch, lift back up, repeat 30 seconds each side, go slow! ",
    "hold plow pose - lay on back with arms down by side. lift legs up and over until they touch the ground above your head, hold",
    "hold fish pose - lay on back with hands under butt. look up and press chest and stomach up into the air, balancing on head",
    "alternating plows - lay on back with head up, one leg out straight off the ground, the other curled into your chest, hug the knee in and then switch",
    "back leg extension - stand with one knee up at a 90 degree angle, bend forward with arms out straight by your ears, kicking the leg that was up straight back, repeat, 30 seconds each side",
    "one-leg squats",
    "bear squats - downward dog, legs slightly apart, squat down, push back up",
    "hamstring curls - lay on stomach, propped on elbows, legs out straight behind you, curl feet up toward but and try to lift thighs up off the ground",
    "rolling squats - do a deep, all-the-way down squat, let it fall back into a roll, then roll back forward and stand again",
    "sumo squats",
    "advanced bridges - get on butt, feet flat on the floor, arms behind you, press up to a table top pose, and lower back down",
    "Heisman shuffle - squat down, come up and lift foot off the ground, go back down to a squat, repeat on other side, never quite reaching back up to straight",
    "frog hold - sit with back straight against wall. Put hands on the ground between your legs, bend legs and lift feet off the floor and hold"
];

const image = 'https://i.imgur.com/4p6atRX.png';

module.exports = {
    exercises,
    image
}